{
  "branches": ["master"],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits",
        "releaseRules": [
          {"type": "feat", "release": "minor"},
          {"type": "fix", "release": "patch"},
          {"type": "perf", "release": "patch"},
          {"breaking": true, "release": "major"}
        ]
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/github"
  ]
}